name: CI/CD Pipeline

on:
  push:
    branches: 
        - main
        - dev
  pull_request:
    branches: 
        - main
        - dev

permissions:
  contents: write

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Run Gitleaks
      run: |
        docker run --rm -v ${{ github.workspace }}:/repo \
          zricethezav/gitleaks:latest \
          detect --source /repo --no-git --verbose --report-format json --report-path /repo/gitleaks-report.json
   
    - name: Upload Gitleaks report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.json

  linting:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    needs: gitleaks
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Tests
        run: ./vendor/bin/pest --coverage --no-interaction
